// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdZQLrLmnEtqRBNNp84_zXQdEILaodJgE',
    appId: '1:276138578675:web:383f3bf1b0ae14b4e89d86',
    messagingSenderId: '276138578675',
    projectId: 'fir-memo-app-3d136',
    authDomain: 'fir-memo-app-3d136.firebaseapp.com',
    storageBucket: 'fir-memo-app-3d136.appspot.com',
    measurementId: 'G-EDZ60WPC27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyIMA3o9eyg8JDZeCAcaUgxwZjvbv5AYU',
    appId: '1:276138578675:android:174dc7c0c8665aece89d86',
    messagingSenderId: '276138578675',
    projectId: 'fir-memo-app-3d136',
    storageBucket: 'fir-memo-app-3d136.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDveWDzGFbBCO2b4nboD0pxLzgan3MzlHg',
    appId: '1:276138578675:ios:db182b0802bd7692e89d86',
    messagingSenderId: '276138578675',
    projectId: 'fir-memo-app-3d136',
    storageBucket: 'fir-memo-app-3d136.appspot.com',
    iosClientId: '276138578675-jdf24gtoadjh5irdb557n14t52ererd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDveWDzGFbBCO2b4nboD0pxLzgan3MzlHg',
    appId: '1:276138578675:ios:db182b0802bd7692e89d86',
    messagingSenderId: '276138578675',
    projectId: 'fir-memo-app-3d136',
    storageBucket: 'fir-memo-app-3d136.appspot.com',
    iosClientId: '276138578675-jdf24gtoadjh5irdb557n14t52ererd2.apps.googleusercontent.com',
    iosBundleId: 'com.example.memoApp',
  );
}
